[package]
name = "capture"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
clueless-types.workspace = true
cpal.workspace = true
screencapturekit.workspace = true
rtrb.workspace = true
tracing.workspace = true

[lints]
workspace = true
