[package]
name = "asr"
edition.workspace = true
version.workspace = true

[dependencies]
clueless-types.workspace = true
reqwest.workspace = true
hound.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
axum.workspace = true
tokio.workspace = true

[lints]
workspace = true
